### ISSUE TITLE
Anpassung der Einheiten des "Bar"-Phidgets

### ISSUE THREAD

**Issue by Kaffeekaethe** [sleighsoft/SWT15-Project-07#15]
### User Story

**Rolle:** Kind / Benutzer
**Ziel/Nutzen:** Umrechnung der durch das "Bar"-Phidget bereitgestellten Daten in gebräuchliche Einheiten und gegebenenfalls Anpassung der Einstellungsintervalle
**Beweggrund:** Erleichterung der Nutzung des Produktes und Erhöhung des Verständis der Daten und Funktion des "Bar-"Phidgets.
### Zeitaufwand

**Benötigte Schritte und Zeitaufwand:**

| Todo | Zeitaufwand |
| --- | --- |
| Recherche: Was misst das Phidget, welche Daten liefert es an den Rechner? | 30 Minuten |
| Recherche: Wie können die bereitgestellten Daten in verständliche Form umgerechnet werden? | 15 Minuten |
| Implementierung der Umrechnung | 1 Std. |
| Anpassung des GUI | 1 Std. |
### Codestellen

```
PhdETBarSensorPort: kilogram, newton, pascal ...
```

**Comment by sebastian-ernst** [comment]
Möglichkeit der Kalibrierung
