### ISSUE TITLE
Anzahl Phidgets auf Anzahl Ports begrenzt

### ISSUE THREAD

**Issue by sleighsoft** [sleighsoft/SWT15-Project-07#21]
### User Story

**Rolle:** Benutzer
**Ziel/Nutzen:** Verhindern, dass mehr Phidgets in Etoys and das Interface Kit angeschlossen werden als Ports vorhanden sind
**Beweggrund:** Verhindert ein Paar merkwürdige Fehler und erleichert die Bedienung und das Verständnis des aktuellen Aufbaus
### Zeitaufwand

**Benötigte Schritte und Zeitaufwand:**

| Todo | Zeitaufwand |
| --- | --- |
| Analyse des Codes | 1 std |
| Implementierung | 3 std |
| Testanpassung | 5 min |
### Codestellen

```
PhdETPortBasedPhidget
    unregisterPort:
    registerPort:
    implementiere checkForFreeConnector: anEvent
        hide/show der PartsBin Elemente

Spezifisches Event handling dann in PhdETAdvancedInterfaceKit

PhdETPort
    portType
        type auf Klassenseite

```

**Comment by Kaffeekaethe** [comment]
Der Joystick sollte auch dann nicht auswählbar sein, wenn nur noch ein Port frei ist, da er zwei Eingänge benötigt. Wenn man einen Joystick bei nur einem offenen Port einbaut, wird der erste Port weiterhin zweifach belegt.
