### ISSUE TITLE
Verbesserung des Phidget Managers

### ISSUE THREAD

**Issue by sleighsoft** [sleighsoft/SWT15-Project-07#4]
### User Story

**Rolle:** Kind + versiertere Benutzer (Betreuer)
**Ziel/Nutzen:** Anzeige einer Übersicht über alle erzeugten InterfaceKits und der an diese angeschlossenen Phidgets (samt Status?). Eine einfache Möglichkeit die InterfaceKits und an diese angeschlossene Geräte bei Bedarf zu löschen.
**Beweggrund:** Einerseits besteht ein Fehler im Programm, bei dem es passieren kann, dass ein InterfaceKit-Objekt existiert, welches den Treiber für die Phidgets blockiert, dieses aber nicht auf dem GUI zu erkennen ist. Dieser Fehler soll somit behoben werden. Andererseits erleichtert es den Umgang mit und die Übersicht über alle vorhandenen Phidgets.
### Zeitaufwand

**Benötigte Schritte und Zeitaufwand:**

| Todo | Zeitaufwand |
| --- | --- |
| Analyse des bestehenden Codes | 2 Std. |
| Implementierung einer Möglichkeit zum Löschen einzelner Interfacekits und deren Phidgets | 1 - 2 Std. |
| Implementierung der Anzeige von an InterfaceKits angeschlossenen Phidgets? | 1 Std. |
| Implementierung der Anzeige des Status jedes im GUI angeschlossenen Bauteils (physisch vorhanden oder nicht?) | 1 Std. |
### Codestellen

```
Class: PhidgetManager
   - Methods:
     closeAndRemoveETPhidget
     createAndAddRemoveButtonFor: aPhidgetNumber


```

**Comment by j-beyer** [comment]
Bug suchen
Design verbessern (Attached Liste, Höhe des PhidgetManagers)
