### ISSUE TITLE
InterfaceKit Input/Output Nummerierung

### ISSUE THREAD

**Issue by sleighsoft** [sleighsoft/SWT15-Project-07#5]
### User Story

**Rolle:** Kind / Benutzer
**Ziel/Nutzen:** Nummerierung der Inputs und Outputs des InterfaceKits im GUI, so wie sie auch am physischen Gerät nummeriert sind
**Beweggrund:** Das Anschließen von Phidgets an das InterfaceKit verständlich gestalten
### Zeitaufwand

**Benötigte Schritte und Zeitaufwand:**

| Todo | Zeitaufwand |
| --- | --- |
| Analyse des bestehnden Codes | Gering |
| Aktualisierung des vorhandenen Images | Gering |
| Evtl. Anpassung der Größe des Kits | Gering |
### Codestellen

```
<Noch kein Code vorhanden, bitte nachtragen>
```

**Comment by sebastian-ernst** [comment]
Nummerierung bei 0 beginnen
